*&---------------------------------------------------------------------*
*& Include          ZCLIENTESPROVEEDORES_GP1_TOP
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

PARAMETERS: P01 RADIOBUTTON GROUP RB1 USER-COMMAND UCC DEFAULT 'X',
            P02 RADIOBUTTON GROUP RB1,
            P03 RADIOBUTTON GROUP RB2 USER-COMMAND UCC DEFAULT 'X',
            P04 RADIOBUTTON GROUP RB2.

SELECTION-SCREEN END OF BLOCK B1.
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.

PARAMETERS: P_KUNNR TYPE ZKUNNR_GP1 MODIF ID MD1,   "---> Hacer obligatorio
            P_LIFNR TYPE ZLIFNR_GP1 MODIF ID MD2,   "---> Hacer obligatorio
            P_NAME1 TYPE ZNAME1_GP_GP1 MODIF ID MD3,
            P_NAME2 TYPE ZNAME2_GP_GP1 MODIF ID MD3,
            P_BUKRS TYPE ZBUKRS_GP1 MODIF ID MD3,
            P_STKZN TYPE ZSTKZN_GP1 MODIF ID MD3,
            P_REGIO TYPE ZREGIO_GP1 MODIF ID MD3,
            P_PSTLZ TYPE ZPSTLZ_GP1 MODIF ID MD3.

DATA: OP_AGREGAR TYPE I VALUE 0,   "---> AGREGAR: 0 ELIMINAR: 1.
      OP_CLIENTE TYPE I VALUE 0.   "---> CLIENTE: 0 PROVEEDOR: 1.

SELECTION-SCREEN END OF BLOCK B2.
*&---------------------------------------------------------------------*

DATA: WA_ZCLIENTES TYPE ZCLIENTES_GP1,
    WA_ZPROVEEDORES TYPE ZPROVEEDORES_GP1,
    WA_CLIENTES_SFACTURA TYPE ZORDENVENTA_GP1,
    WA_PROVEEDORES_SFACTURA TYPE ZORDENCOMPRA_GP1,
    WA_ZCLIENTES_AUX TYPE ZCLIENTES_GP1,
    WA_ZPROVEEDORES_AUX TYPE ZCLIENTES_GP1,
    GT_CLIENTES_SFACTURA TYPE STANDARD TABLE OF ZORDENVENTA_GP1,
    GT_PROVEEDORES_SFACTURA TYPE STANDARD TABLE OF ZORDENCOMPRA_GP1.
*&---------------------------------------------------------------------*

DATA: BDC_TAB TYPE TABLE OF BDCDATA,  "---> Batch Input
      WA_BDC_TAB TYPE BDCDATA.